import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {

  const user = useUser()

  const { data } = api.books.getAll.useQuery()

  return (
    <>
      <Head>
        <title>Book Keeper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/book-stack.png" />
      </Head>
      <main className="flex min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {user.isSignedIn && <SignOutButton />}
        </div>
      </main>
    </>
  );
};

export default Home;
