import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  const { data } = api.books.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Book Keeper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/book-stack.png" />
      </Head>
      <main className="flex min-h-screen">
        <div className="m-auto grid grid-cols-1 gap-3 p-4 sm:grid-cols-2 lg:grid-cols-3">
          {/* {user.isSignedIn ? <SignOutButton /> : <SignInButton />} */}
          <div className="max-w-xs overflow-hidden rounded bg-slate-950 py-4 shadow-lg">
            <img
              src="https://placehold.co/200x250?text=Book+Cover&font=roboto"
              alt="Book Keeper"
              className="m-auto flex justify-center rounded shadow-sm shadow-slate-400"
            />
            <div className="px-5 py-4">
              <div className="mb-2 text-xl font-bold text-violet-300">
                Book Title
              </div>
              <p className="text-sm text-slate-700">
                lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis,
                architecto?
              </p>
            </div>
            <div className="flex items-center px-5 py-2">
              {/* user image */}
              <div className="text-sm">
                <p className="leading-none text-slate-700">User name</p>
              </div>
            </div>
          </div>

          <div className="max-w-xs overflow-hidden rounded bg-slate-950 py-4 shadow-lg">
            <img
              src="https://placehold.co/200x250?text=Book+Cover&font=roboto"
              alt="Book Keeper"
              className="m-auto flex justify-center rounded shadow-sm shadow-slate-400"
            />
            <div className="px-5 py-4">
              <div className="mb-2 text-xl font-bold text-violet-300">
                Book Title
              </div>
              <p className="text-sm text-slate-700">
                lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis,
                architecto?
              </p>
            </div>
            <div className="flex items-center px-5 py-2">
              {/* user image */}
              <div className="text-sm">
                <p className="leading-none text-slate-700">User name</p>
              </div>
            </div>
          </div>

          <div className="max-w-xs overflow-hidden rounded bg-slate-950 py-4 shadow-lg">
            <img
              src="https://placehold.co/200x250?text=Book+Cover&font=roboto"
              alt="Book Keeper"
              className="m-auto flex justify-center rounded shadow-sm shadow-slate-400"
            />
            <div className="px-5 py-4">
              <div className="mb-2 text-xl font-bold text-violet-300">
                Book Title
              </div>
              <p className="text-sm text-slate-700">
                lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis,
                architecto?
              </p>
            </div>
            <div className="flex items-center px-5 py-2">
              {/* user image */}
              <div className="text-sm">
                <p className="leading-none text-slate-700">User name</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
